GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Groceries"
}

###

DELETE http://localhost:3001/todo/delete/

###

GET http://localhost:3001/todo/complete/